version: "3"

volumes:
   cache_dir:
services:
 postgres:
   restart: always
   image: postgres:latest
   environment:
     POSTGRES_USER: openoversight
     POSTGRES_PASSWORD: terriblepassword
     POSTGRES_DB: openoversight-dev

 web:
   restart: always
   build:
      context: .
      args:
      - DOCKER_BUILD_ENV
      dockerfile: ./dockerfiles/web/Dockerfile
   environment:
     AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
     AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
     AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
     S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
     HMR: 1
   volumes:
     - ./OpenOversight/:/usr/src/app/OpenOversight/
     - /usr/src/app/OpenOversight/static/dist/
   links:
     - postgres:postgres
   expose:
     - "3000"
   command: scripts/entrypoint.sh
   ports:
     - "3000:3000"
     - "3001:3001"
     - "5433:5432"
